### ISSUE TITLE
Automate updating versing of 'go' 

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/.github#36]
## Motivation

Updating version of 'go' is a very monotonous and most importantly time-consuming task since we need to update all our repositories (https://github.com/networkservicemesh?q=&type=all&language=go&sort= we have 54  repos)

## Solution

Create a workflow that will update all repos automatically.

## Implementation (DRAFT)

1. The user with admin rights creates a branch in .github repo`update/go_${version}` 
2. NSMBot creates PR into .github repo where update version of go (simply replaces string with version https://github.com/networkservicemesh/.github/blob/main/.github/workflows/build-and-test.yaml to new version from the branch name)
3. NSMBot merges the branch if everyting is OK
4. Right after merge the branch, workflow triggers and starts update other go repos. (We could re-use our expirience with releaing and use workflow_run event https://github.com/networkservicemesh/sdk/blob/main/.github/workflows/release.yaml#L3-L8)
5. The workflow uses matrix and  fetch org job https://github.com/networkservicemesh/cmd-template/blob/main/.github/workflows/update-cmd-repositories.yaml#L9-L20 to get the list of repos
6. Checkout repo from the list https://github.com/networkservicemesh/cmd-template/blob/main/.github/workflows/update-cmd-repositories.yaml#L30-L35
7. replace strings with go version in go mod and  in `./workflow` folder
8. install new version of go
9. run go mod tidy
10. if Dockerfile is exsist then we should update version of the docker image https://github.com/networkservicemesh/cmd-nsc/blob/main/Dockerfile#L1
11. commit changes as NSMBot  and open PR (just push a brach `update/go_$version` into target repo)
12. NSMBot automaticcaly will create a PR and if ci will pass then the update will be merged (this step is already done)

**Comment by bellycat77** [comment]
Current results are here: https://github.com/bellycat77/nsm-.github/tree/update-go-version-automation
This branch release steps 1-3

**Comment by NikitaSkrynnik** [comment]
It looks like it's impossible to automate updating Go version. Here is a table of history of updating Go Version
https://docs.google.com/spreadsheets/d/1i4iTyyNLmcKBXaMLKN9X6PRpjkulnUgjhsey6QsYo8c/edit?usp=sharing

As you can see there was only one case with updating Go from 1.15 to 1.16 which would work using a new workflow from [this PR](https://github.com/networkservicemesh/.github/pull/43). Other updates would work partially.
