### ISSUE TITLE
Add CVE scanner

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/.github#49]

**Comment by dualBreath** [comment]
Dependency check scanner: https://github.com/jeremylong/DependencyCheck
Some results for the dependency scanner and repositories used in cmd-forvarder-vpp: https://docs.google.com/spreadsheets/d/10OYz_sHUVsFZBCX16vsYaDCqV19FsZY7VZ_O2wq3j28/edit?usp=sharing

**Comment by dualBreath** [comment]
Trivy scanner: https://github.com/aquasecurity/trivy

Example of output for `api` repository and commit `c4a3ece88804b49d1b2c800609388319af3cc47f`:

![Screenshot 2023-11-10 at 15 02 23](https://github.com/networkservicemesh/.github/assets/10182393/1cfdd83f-3f42-4285-8cdd-95db73d946e2)

**Comment by dualBreath** [comment]
For now we have decided to use the docker CVE image scanner: https://github.com/networkservicemesh/deployments-k8s/pull/10353
