### ISSUE TITLE
Use Github CLI to create releases

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/.github#58]
Our release workflow [uses Github Action](https://github.com/networkservicemesh/.github/blob/main/.github/workflows/release.yaml#L36) that hasn't been supported [since 2021](https://github.com/actions/create-release). We should use Github CLI instead:

```
gh release create "${tag}" --title="${title}"
```

**Comment by denis-tingaikin** [comment]
Could you have a look at https://github.com/networkservicemesh/deployments-k8s/actions/runs/8523691185/job/23347838943?

**Comment by denis-tingaikin** [comment]
Seems like done. Thanks!§
