### ISSUE TITLE
Keep env var descriptions in sync in cmd and README.md

### ISSUE THREAD

**Issue by arp-est** [networkservicemesh/.github#65]
Goal is to have something that checks whether the envs in the README match the ones described by the cmd.

**Comment by arp-est** [comment]
Hi,
Added the pr-s to cmd-template, and k8s-deployment too.

https://github.com/networkservicemesh/cmd-registry-memory/pull/661
https://github.com/networkservicemesh/deployments-k8s/pull/11877
https://github.com/networkservicemesh/cmd-template/pull/131

**Comment by arp-est** [comment]
Hi, 
Updated the cmd-s, fixed the bug in .github/scripts/env-check.sh, and updated the env vars that were changed in deployments-k8s.

Pull Requests:

https://github.com/networkservicemesh/.github/pull/76
https://github.com/networkservicemesh/cmd-admission-webhook-k8s/pull/421
https://github.com/networkservicemesh/cmd-cluster-info-k8s/pull/129
https://github.com/networkservicemesh/cmd-csi-driver/pull/64
https://github.com/networkservicemesh/cmd-exclude-prefixes-k8s/pull/293
https://github.com/networkservicemesh/cmd-forwarder-ovs/pull/370
https://github.com/networkservicemesh/cmd-forwarder-sriov/pull/731
https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/1105
https://github.com/networkservicemesh/cmd-ipam-vl3/pull/196
https://github.com/networkservicemesh/cmd-lb-vl3-vpp/pull/73
https://github.com/networkservicemesh/cmd-map-ip-k8s/pull/218
https://github.com/networkservicemesh/cmd-nsc/pull/627
https://github.com/networkservicemesh/cmd-nsc-init/pull/741
https://github.com/networkservicemesh/cmd-nsc-simple-docker/pull/224
https://github.com/networkservicemesh/cmd-nsc-vpp/pull/690
https://github.com/networkservicemesh/cmd-nse-firewall-vpp/pull/508
https://github.com/networkservicemesh/cmd-nse-icmp-responder/pull/593
https://github.com/networkservicemesh/cmd-nse-icmp-responder-vpp/pull/671
https://github.com/networkservicemesh/cmd-nse-l7-proxy/pull/201
https://github.com/networkservicemesh/cmd-nse-remote-vlan/pull/223
https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/pull/237
https://github.com/networkservicemesh/cmd-nse-supplier-k8s/pull/329
https://github.com/networkservicemesh/cmd-nse-vfio/pull/514
https://github.com/networkservicemesh/cmd-nse-vl3-vpp/pull/332
https://github.com/networkservicemesh/cmd-nse-vlan-vpp/pull/467
https://github.com/networkservicemesh/cmd-nsmgr/pull/677
https://github.com/networkservicemesh/cmd-nsmgr-proxy/pull/496
https://github.com/networkservicemesh/deployments-k8s/pull/11916

Envs that got split_words:"true" added:
(might include envs from deprecated repos, have to check it)

NSM_ACL_CONFIG
NSM_BRIDGE_NAME
NSM_FEDERATES_WITH
NSM_INTERFACE_NAME
NSM_LIVENESS_CHECK_ENABLED
NSM_LIVENESS_CHECK_INTERVAL
NSM_LIVENESS_CHECK_TIMEOUT
NSM_LOCAL_DNS_SERVER_ADDRESS
NSM_LOCAL_DNS_SERVER_ENABLED
NSM_METRICS_EXPORT_INTERVAL
NSM_NODE_NAME
NSM_OPEN_TELEMETRY_ENDPOINT
NSM_OUTPUT_PATH
NSM_TRUST_DOMAIN
NSM_VL3_PREFIX

**Comment by denis-tingaikin** [comment]
Great work, thanks! 

It seems like a few repos are still remaining. Could you also have a look at https://github.com/networkservicemesh?q=registry-&type=all&language=&sort=?

**Comment by arp-est** [comment]
Hi,
Sorry about that I forgot to create the pull request for those.
Here they are now:
https://github.com/networkservicemesh/cmd-registry-proxy-dns/pull/647
https://github.com/networkservicemesh/cmd-registry-memory/pull/666
https://github.com/networkservicemesh/cmd-registry-k8s/pull/457 (I see that you already merged this one)

**Comment by denis-tingaikin** [comment]
All good. Merged.
