### ISSUE TITLE
CI/CD: Replace github actions in `automerge` workflow with GitHub CLI

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/.github#71]
Rework `automerge` action in:
1. [.github](https://github.com/networkservicemesh/.github/blob/main/.github/workflows/automerge.yaml)
2. [deployments-k8s](https://github.com/networkservicemesh/deployments-k8s/blob/main/.github/workflows/automerge.yaml)
3. All integration repos

**Comment by denis-tingaikin** [comment]
Seems like done. We'll reopen the ticket if face any problems on CI.
